[project]
name = "snaptosign"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "anndata>=0.10.9",
    "numpy>=1.26.4",
    "pandas>=2.1.1",
    "scanpy>=1.11.5",
    "snapatac2>=2.8.0",
]
